In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel("../data/Cleaned_Superstore.xlsx")

In [3]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [4]:
df.shape

(9977, 13)

# Overall KPI Summary

In [5]:
kpi_summary = pd.DataFrame({
    "KPI": [
        "Total Sales",
        "Total Profit",
        "Average Sales",
        "Average Profit",
        "Total Quantity Sold",
        "Average Discount"
    ],
    "Value": [
        round(df["Sales"].sum(), 2),
        round(df["Profit"].sum(), 2),
        round(df["Sales"].mean(), 2),
        round(df["Profit"].mean(), 2),
        int(df["Quantity"].sum()),
        round(df["Discount"].mean(), 2)
    ]
})

kpi_summary

                   KPI       Value
0          Total Sales  2296195.59
1         Total Profit   286241.42
2        Average Sales      230.15
3       Average Profit       28.69
4  Total Quantity Sold    37820.00
5     Average Discount        0.16

In [6]:
kpi_summary.to_excel("../data/kpi_summary.xlsx", index=False)

In [7]:
import os

os.listdir("../data")

['.ipynb_checkpoints',
 'Cleaned_Superstore.xlsx',
 'kpi_summary.xlsx',
 'SampleSuperstore.xlsx']

# Category KPI Summary

In [8]:
category_kpi = df.groupby("Category").agg({
    "Sales":"sum",
    "Profit":"sum",
    "Quantity":"sum",
    "Discount":"mean"
}).reset_index()

category_kpi["Sales"] = category_kpi["Sales"].round(2)
category_kpi["Profit"] = category_kpi["Profit"].round(2)
category_kpi["Discount"] = category_kpi["Discount"].round(2)

category_kpi

          Category      Sales     Profit  Quantity  Discount
0        Furniture  741306.31   18421.81      8020      0.17
1  Office Supplies  718735.24  122364.66     22861      0.16
2       Technology  836154.03  145454.95      6939      0.13

In [9]:
category_kpi.to_excel("../data/category_kpi_summary.xlsx", index=False)

# Create Region KPI Summary

In [10]:
region_kpi = df.groupby("Region").agg({
    "Sales": "sum",
    "Profit": "sum",
    "Quantity": "sum",
    "Discount": "mean"
}).reset_index()

region_kpi["Sales"] = region_kpi["Sales"].round(2)
region_kpi["Profit"] = region_kpi["Profit"].round(2)
region_kpi["Discount"] = region_kpi["Discount"].round(2)

region_kpi

    Region      Sales     Profit  Quantity  Discount
0  Central  500782.85   39655.88      8768      0.24
1     East  678435.20   91506.31     10609      0.15
2    South  391721.90   46749.43      6209      0.15
3     West  725255.64  108329.81     12234      0.11

In [11]:
region_kpi.to_excel("../data/region_kpi_summary.xlsx", index=False)

# State KPI Summary

In [12]:
state_kpi = df.groupby("State").agg({
    "Sales": "sum",
    "Profit": "sum",
    "Quantity": "sum",
    "Discount": "mean"
}).reset_index()

state_kpi["Sales"] = state_kpi["Sales"].round(2)
state_kpi["Profit"] = state_kpi["Profit"].round(2)
state_kpi["Discount"] = state_kpi["Discount"].round(2)

state_kpi

                   State      Sales    Profit  Quantity  Discount
0                Alabama   19510.64   5786.83       256      0.00
1                Arizona   35282.00  -3427.92       862      0.30
2               Arkansas   11678.13   4008.69       240      0.00
3             California  457576.27  76330.79      7649      0.07
4               Colorado   32108.12  -6527.86       693      0.32
5            Connecticut   13384.36   3511.49       281      0.01
6               Delaware   27451.07   9977.37       367      0.01
7   District of Columbia    2865.02   1059.59        40      0.00
8                Florida   89473.71  -3399.30      1379      0.30
9                Georgia   49095.84  16250.04       705      0.00
10                 Idaho    4382.49    826.72        64      0.09
11              Illinois   80162.54 -12601.65      1842      0.39
12               Indiana   53555.36  18382.94       578      0.00
13                  Iowa    4579.76   1183.81       112      0.00
14                Kansas    2914.31    836.44        74      0.00
15              Kentucky   36591.75  11199.70       523      0.00
16             Louisiana    9217.03   2196.10       156      0.00
17                 Maine    1270.53    454.49        35      0.00
18              Maryland   23705.52   7031.18       420      0.01
19         Massachusetts   28634.43   6785.50       491      0.02
20              Michigan   75879.64  24428.09       943      0.01
21             Minnesota   29863.15  10823.19       331      0.00
22           Mississippi   10771.34   3172.98       221      0.00
23              Missouri   22205.15   6436.21       252      0.00
24               Montana    5589.35   1833.33        56      0.07
25              Nebraska    7464.93   2037.09       136      0.00
26                Nevada   16729.10   3316.77       168      0.06
27         New Hampshire    7292.52   1706.50       127      0.01
28            New Jersey   35764.31   9772.91       454      0.00
29            New Mexico    4783.52   1157.12       151      0.06
30              New York  310827.15  74015.46      4220      0.06
31        North Carolina   55603.16  -7490.91       983      0.28
32          North Dakota     919.91    230.15        30      0.00
33                  Ohio   77976.76 -16959.32      1757      0.32
34              Oklahoma   19683.39   4853.96       247      0.00
35                Oregon   17420.78  -1194.10       497      0.29
36          Pennsylvania  116496.36 -15565.40      2150      0.33
37          Rhode Island   22627.96   7285.63       199      0.02
38        South Carolina    8481.71   1769.06       172      0.00
39          South Dakota    1315.56    394.83        42      0.00
40             Tennessee   30661.87  -5341.69       681      0.29
41                 Texas  170124.54 -25750.98      3718      0.37
42                  Utah   11220.06   2546.53       219      0.06
43               Vermont    8929.37   2244.98        50      0.00
44              Virginia   70636.72  18597.95       893      0.00
45            Washington  138560.81  33368.24      1871      0.06
46         West Virginia    1209.82    185.92        18      0.08
47             Wisconsin   32114.61   8401.80       463      0.00
48               Wyoming    1603.14    100.20         4      0.20

In [13]:
state_kpi.to_excel("../data/state_kpi_summary.xlsx", index=False)

# Sub-Category KPI Summary

In [14]:
subcategory_kpi = df.groupby("Sub-Category").agg({
    "Sales": "sum",
    "Profit": "sum",
    "Quantity": "sum",
    "Discount": "mean"
}).reset_index()

subcategory_kpi["Sales"] = subcategory_kpi["Sales"].round(2)
subcategory_kpi["Profit"] = subcategory_kpi["Profit"].round(2)
subcategory_kpi["Discount"] = subcategory_kpi["Discount"].round(2)

subcategory_kpi

   Sub-Category      Sales    Profit  Quantity  Discount
0   Accessories  167380.32  41936.64      2976      0.08
1    Appliances  107532.16  18138.01      1729      0.17
2           Art   27107.03   6524.61      2996      0.07
3       Binders  203409.17  30228.00      5971      0.37
4     Bookcases  114880.00  -3472.56       868      0.21
5        Chairs  327777.76  26567.13      2351      0.17
6       Copiers  149528.03  55617.82       234      0.16
7     Envelopes   16476.40   6964.18       906      0.08
8     Fasteners    3024.28    949.52       914      0.08
9   Furnishings   91683.02  13052.72      3560      0.14
10       Labels   12444.91   5526.38      1396      0.07
11     Machines  189238.63   3384.76       440      0.31
12        Paper   78224.14  33944.24      5144      0.07
13       Phones  330007.05  44515.73      3289      0.15
14      Storage  223843.61  21278.83      3158      0.07
15     Supplies   46673.54  -1189.10       647      0.08
16       Tables  206965.53 -17725.48      1241      0.26

In [15]:
subcategory_kpi.to_excel("../data/subcategory_kpi_summary.xlsx", index=False)

# Segment KPI Summary

In [16]:
segment_kpi = df.groupby("Segment").agg({
    "Sales": "sum",
    "Profit": "sum",
    "Quantity": "sum",
    "Discount": "mean"
}).reset_index()

segment_kpi["Sales"] = segment_kpi["Sales"].round(2)
segment_kpi["Profit"] = segment_kpi["Profit"].round(2)
segment_kpi["Discount"] = segment_kpi["Discount"].round(2)

segment_kpi

       Segment       Sales     Profit  Quantity  Discount
0     Consumer  1160832.77  134007.44     19497      0.16
1    Corporate   706070.13   91954.98     11591      0.16
2  Home Office   429292.68   60279.00      6732      0.15

In [17]:
segment_kpi.to_excel("../data/segment_kpi_summary.xlsx", index=False)

# Ship Mode KPI Summary

In [18]:
shipmode_kpi = df.groupby("Ship Mode").agg({
    "Sales": "sum",
    "Profit": "sum",
    "Quantity": "sum",
    "Discount": "mean"
}).reset_index()

shipmode_kpi["Sales"] = shipmode_kpi["Sales"].round(2)
shipmode_kpi["Profit"] = shipmode_kpi["Profit"].round(2)
shipmode_kpi["Discount"] = shipmode_kpi["Discount"].round(2)

shipmode_kpi

        Ship Mode       Sales     Profit  Quantity  Discount
0     First Class   351380.47   48953.66      5690      0.16
1        Same Day   128321.72   15871.89      1956      0.15
2    Second Class   459177.05   57446.65      7418      0.14
3  Standard Class  1357316.35  163969.23     22756      0.16

In [19]:
shipmode_kpi.to_excel("../data/shipmode_kpi_summary.xlsx", index=False)