In [1]:
import pandas as pd
import sqlite3

In [2]:
df = pd.read_excel("../data/Cleaned_Superstore.xlsx")

In [3]:
df.head()

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [4]:
df.shape

(9977, 13)

In [5]:
conn = sqlite3.connect("../data/business_kpi.db")

In [6]:
df.to_sql("sales_data", conn, if_exists="replace", index=False)

9977

In [7]:
query = "SELECT * FROM sales_data LIMIT 5;"
pd.read_sql(query, conn)

,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub-Category,Sales,Quantity,Discount,Profit
0,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,261.9600,2,0.00,41.9136
1,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,731.9400,3,0.00,219.5820
2,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,14.6200,2,0.00,6.8714
3,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,957.5775,5,0.45,-383.0310
4,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,22.3680,2,0.20,2.5164

In [8]:
query = """
SELECT SUM(Sales) AS Total_Sales
FROM sales_data;
"""

pd.read_sql(query, conn)

    Total_Sales
0  2.296196e+06

In [9]:
query = """
SELECT SUM(Profit) AS Total_Profit
FROM sales_data;
"""

pd.read_sql(query, conn)

   Total_Profit
0   286241.4226

In [10]:
query = """
SELECT ROUND(AVG(Sales),2) AS Average_Sales
FROM sales_data;
"""

pd.read_sql(query, conn)

   Average_Sales
0         230.15

In [11]:
query = """
SELECT ROUND(AVG(Profit),2) AS Average_Profit
FROM sales_data;
"""

pd.read_sql(query, conn)

   Average_Profit
0           28.69

In [12]:
query = """
SELECT SUM(Quantity) AS Total_Quantity
FROM sales_data;
"""

pd.read_sql(query, conn)

   Total_Quantity
0           37820

In [13]:
query = """
SELECT Category,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM sales_data
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0       Technology    836154.03
1        Furniture    741306.31
2  Office Supplies    718735.24

In [14]:
query = """
SELECT Category,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM sales_data
GROUP BY Category
ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Profit
0       Technology     145454.95
1  Office Supplies     122364.66
2        Furniture      18421.81

In [15]:
query = """
SELECT Region,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM sales_data
GROUP BY Region
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

    Region  Total_Sales
0     West    725255.64
1     East    678435.20
2  Central    500782.85
3    South    391721.91

In [16]:
query = """
SELECT Region,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM sales_data
GROUP BY Region
ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, conn)

    Region  Total_Profit
0     West     108329.81
1     East      91506.31
2    South      46749.43
3  Central      39655.88

In [17]:
query = """
SELECT [Ship Mode],
       ROUND(SUM(Sales),2) AS Total_Sales
FROM sales_data
GROUP BY [Ship Mode]
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

        Ship Mode  Total_Sales
0  Standard Class   1357316.35
1    Second Class    459177.05
2     First Class    351380.47
3        Same Day    128321.73

In [18]:
query = """
SELECT [Ship Mode],
       ROUND(SUM(Profit),2) AS Total_Profit
FROM sales_data
GROUP BY [Ship Mode]
ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, conn)

        Ship Mode  Total_Profit
0  Standard Class     163969.23
1    Second Class      57446.65
2     First Class      48953.66
3        Same Day      15871.89

In [19]:
query = """
SELECT State,
       ROUND(SUM(Sales),2) AS Total_Sales
FROM sales_data
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

          State  Total_Sales
0    California    457576.27
1      New York    310827.15
2         Texas    170124.54
3    Washington    138560.81
4  Pennsylvania    116496.36
5       Florida     89473.71
6      Illinois     80162.54
7          Ohio     77976.76
8      Michigan     75879.64
9      Virginia     70636.72

In [20]:
query = """
SELECT State,
       ROUND(SUM(Profit),2) AS Total_Profit
FROM sales_data
GROUP BY State
ORDER BY Total_Profit DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

        State  Total_Profit
0  California      76330.79
1    New York      74015.46
2  Washington      33368.24
3    Michigan      24428.09
4    Virginia      18597.95
5     Indiana      18382.94
6     Georgia      16250.04
7    Kentucky      11199.70
8   Minnesota      10823.19
9    Delaware       9977.37

In [21]:
query = """
SELECT [Sub-Category],
       ROUND(SUM(Sales),2) AS Total_Sales
FROM sales_data
GROUP BY [Sub-Category]
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

   Sub-Category  Total_Sales
0        Phones    330007.05
1        Chairs    327777.76
2       Storage    223843.61
3        Tables    206965.53
4       Binders    203409.17
5      Machines    189238.63
6   Accessories    167380.32
7       Copiers    149528.03
8     Bookcases    114880.00
9    Appliances    107532.16
10  Furnishings     91683.02
11        Paper     78224.14
12     Supplies     46673.54
13          Art     27107.03
14    Envelopes     16476.40
15       Labels     12444.91
16    Fasteners      3024.28

In [22]:
query = """
SELECT [Sub-Category],
       ROUND(SUM(Profit),2) AS Total_Profit
FROM sales_data
GROUP BY [Sub-Category]
ORDER BY Total_Profit DESC;
"""

pd.read_sql(query, conn)

   Sub-Category  Total_Profit
0       Copiers      55617.82
1        Phones      44515.73
2   Accessories      41936.64
3         Paper      33944.24
4       Binders      30228.00
5        Chairs      26567.13
6       Storage      21278.83
7    Appliances      18138.01
8   Furnishings      13052.72
9     Envelopes       6964.18
10          Art       6524.61
11       Labels       5526.38
12     Machines       3384.76
13    Fasteners        949.52
14     Supplies      -1189.10
15    Bookcases      -3472.56
16       Tables     -17725.48

In [23]:
query = """
SELECT [Sub-Category],
       ROUND(SUM(Profit),2) AS Total_Profit
FROM sales_data
GROUP BY [Sub-Category]
ORDER BY Total_Profit ASC
LIMIT 5;
"""

pd.read_sql(query, conn)

  Sub-Category  Total_Profit
0       Tables     -17725.48
1    Bookcases      -3472.56
2     Supplies      -1189.10
3    Fasteners        949.52
4     Machines       3384.76

In [24]:
query = """
SELECT ROUND(AVG(Discount),2) AS Average_Discount
FROM sales_data;
"""

pd.read_sql(query, conn)

   Average_Discount
0              0.16

In [25]:
query = """
SELECT Sales,
       Profit,
       Quantity,
       Discount
FROM sales_data;
"""

corr_df = pd.read_sql(query, conn)
corr_df.head()

      Sales    Profit  Quantity  Discount
0  261.9600   41.9136         2      0.00
1  731.9400  219.5820         3      0.00
2   14.6200    6.8714         2      0.00
3  957.5775 -383.0310         5      0.45
4   22.3680    2.5164         2      0.20

In [26]:
corr_df.corr()

             Sales    Profit  Quantity  Discount
Sales     1.000000  0.479067  0.200722 -0.028311
Profit    0.479067  1.000000  0.066211 -0.219662
Quantity  0.200722  0.066211  1.000000  0.008678
Discount -0.028311 -0.219662  0.008678  1.000000

In [27]:
conn.close()